// <auto-generated />
using System;
using FinanceDashboard.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceDashboard.Service.Migrations
{
    [DbContext(typeof(FinanceDashboardContext))]
    partial class FinanceDashboardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinanceDashboard.Data.Entities.User.User", b =>
                {
                    b.Property<int>("AccpuntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccpuntId"), 1L, 1);

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashingSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("InvalidPasswordCount")
                        .HasColumnType("smallint");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHashHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondFactorKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SecondFactorValidated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("AccpuntId", "Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            AccpuntId = 1,
                            Id = new Guid("e7f52b42-b802-4d1e-a029-9aff55f18d56"),
                            CreatedOn = new DateTime(2022, 8, 31, 17, 6, 45, 721, DateTimeKind.Local).AddTicks(8447),
                            Email = "atishay1928@outlook.com",
                            FirstName = "Atishay",
                            HashingSalt = "==4d8dh51d9c",
                            LastName = "Vishwakarma",
                            MobileNumber = "9827766387",
                            Name = "Atishay Vishwakarma",
                            PasswordHash = "FSZ2d17i8jn8wewbvMuht62CYYaohPtv3b8xzlMGHTA=",
                            PasswordHashHistory = "FSZ2d17i8jn8wewbvMuht62CYYaohPtv3b8xzlMGHTA=,"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
